export const SET_CHARACTER_ID = 'SET_CHARACTER_ID'
export const DELETE_CHARACTER_ID = 'DELETE_CHARACTER_ID'
export const ADD_FAVORITE = 'ADD_FAVORITE'
export const DELETE_FAVORITE = 'DELETE_FAVORITE'
